[package]
name = "async-mailer-core"
description = "Internal core crate for `async-mailer`."
license = "MPL-2.0"
repository = "https://github.com/LeoniePhiline/async-mailer/core"
documentation = "https://docs.rs/async-mailer-core/"
version = "0.3.1"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
async-trait = "0.1.79"
mail-send = { version = "0.4.1", default-features = false, features = ["builder"] }
secrecy = "0.8.0"
thiserror = "1.0.58"
tracing = { optional = true, version = "0.1.37" }
