[package]
name = "async-mailer-core"
description = "Internal core crate for `async-mailer`."
license = "MPL-2.0"
version = "0.1.0"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
async-trait = "0.1.68"
mail-send = { version = "0.3.3", default-features = false, features = ["builder"] }
secrecy = "0.8.0"
thiserror = "1.0.38"
tracing = { optional = true, version = "0.1.37" }
