[package]
name = "async-mailer-smtp"
version = "0.1.0"
edition = "2021"

[features]
default = ["tracing"]
tracing = ["dep:tracing"]

[dependencies]
async-mailer-core = { path = "../core", version = "0.1" }
async-trait = "0.1.68"
secrecy = "0.8.0"
thiserror = "1.0.38"
tracing = { optional = true, version = "0.1.37" }
